xk
minemile/eventfinder pull request #2
Opened 2018-02-07 21:38 UTC by coffman21

now bot works and can interact with database using `MainController`

2018-02-09 08:14 UTC, minemile requested changes

2018-02-09 08:14 UTC, minemile commented on src/main/java/com/banditos/server/bot/Bot.java
> +                String token = new BufferedReader(
Дичь. Значения из ресурсов по-другому получают

2018-02-09 08:14 UTC, minemile commented on src/main/python/ParserExample.py
> +cnx = psycopg2.connect("dbname='eventfinder' user='postgres' host='localhost' password='1234qwer'")
Щас бы пароли в коде хранить.

2018-02-09 08:14 UTC, minemile commented on src/main/python/ParserExample.py
> +cnx = psycopg2.connect("dbname='eventfinder' user='postgres' host='localhost' password='1234qwer'")
Да и вообще зачем тебе парсер на пистоне.

2018-02-09 08:14 UTC, minemile commented on src/main/java/com/banditos/server/bot/Bot.java
> +            SendMessage response = BotMessageCreator.createTusovkasMessage(chatId);
Криво как-то выглядит создание респонса. Ты либо декомпозируешь полностью(один класс для создания респонса, один для создания месседжей, другой "прокси" для похода в бд), либо засовываешь все в этот класс.

2018-02-09 08:29 UTC, coffman21 commented on src/main/java/com/banditos/server/bot/Bot.java
> +                String token = new BufferedReader(
тогда закидываем все в application.properties и читаем оттуда

2018-02-09 08:31 UTC, coffman21 commented on src/main/python/ParserExample.py
> +cnx = psycopg2.connect("dbname='eventfinder' user='postgres' host='localhost' password='1234qwer'")
так это от базы ) ну и он разумеется не нужен, просто твой парсер не сохранял в базу, хотел по-быстрому проверить

2018-02-09 08:33 UTC, coffman21 commented on src/main/java/com/banditos/server/bot/Bot.java
> +            SendMessage response = BotMessageCreator.createTusovkasMessage(chatId);
месседж создает пользователь. предполагается, что отдавать придется разные виды SendMessage, и собирать их будем в BotMessageCreator

2018-02-13 14:22 UTC, minemile requested changes

2018-02-13 14:22 UTC, minemile commented on pom.xml
> +			<scope>runtime</scope>
А как юзать эту штуку?

2018-02-13 14:22 UTC, minemile commented on postgres-docker.sh
> +docker container start psql
Что с этим делать?

2018-02-13 14:22 UTC, minemile commented on src/main/java/com/banditos/server/bot/Bot.java
> +        Bot.telegramToken = env.getProperty("telegram.token");
https://stackoverflow.com/questions/30528255/how-to-access-a-value-defined-in-the-application-properties-file-in-spring-boot
Так и думал, что нужно по-другому делать

2018-02-13 14:22 UTC, minemile commented on src/main/java/com/banditos/server/bot/Bot.java
> +    public void onUpdatesReceived(List<Update> updates) {
В каком случае это вызывается?

2018-02-13 14:22 UTC, minemile commented on src/main/java/com/banditos/server/bot/BotMessageController.java
> +    public static void setMessage(org.telegram.telegrambots.api.objects.Message message) {
Классная переменная. Запихни в импорты

2018-02-13 14:22 UTC, minemile commented on src/main/java/com/banditos/server/bot/BotMessageCreator.java
> +        Iterable<Tusovka> tusovkas = tusovkaRepository.findAll();
Надеюсь это тестовый вариант, иначе зачем всю базу в одно сообщение запихивать?

2018-02-13 14:22 UTC, minemile commented on src/main/java/com/banditos/server/bot/BotMessageCreator.java
> +        Iterable<Tusovka> tusovkas = tusovkaRepository.findAll();
Честно говоря до сих пор не понимаю, почему это отдельный класс

2018-02-13 14:22 UTC, minemile commented on src/main/java/com/banditos/server/parser/AbstractVkParser.java
> +        tusovkaRepository.save(tusovkas);
Зачем ты логику сохранения то запихнул сюда. Эти парсеры будут отдавать только листы с объектами Tusovka

2018-02-13 14:22 UTC, minemile commented on src/main/java/com/banditos/server/parser/AbstractVkParser.java
> +        tusovkaRepository.save(tusovkas);
В абстрактном классе реализация. Здорово!

2018-02-13 14:22 UTC, minemile commented on src/main/resources/example-application.properties
> +vk.appid=
На ямл исправть - лучше читается.

2018-02-13 14:46 UTC, coffman21 commented on pom.xml
> +			<scope>runtime</scope>
ты добавил, ты и расскажи :D

2018-02-13 14:46 UTC, coffman21 commented on postgres-docker.sh
> +docker container start psql
я добавил в Before launch в идее, запускается перед проектом

2018-02-13 14:48 UTC, coffman21 commented on src/main/java/com/banditos/server/bot/Bot.java
> +        Bot.telegramToken = env.getProperty("telegram.token");
Не нужно, а можно. Нужно делать через `@ConfigurationProperties`, но если тебе очень надо именно так - сделай сам

2018-02-13 14:49 UTC, coffman21 commented on src/main/java/com/banditos/server/bot/Bot.java
> +    public void onUpdatesReceived(List<Update> updates) {
когда приходят обновления 🤷‍♂️

2018-02-13 14:50 UTC, coffman21 commented on src/main/java/com/banditos/server/bot/BotMessageController.java
> +    public static void setMessage(org.telegram.telegrambots.api.objects.Message message) {
Ты слепошарый, блядь? Ты видишь, что там два класса с названием Message и разными classpath? Это бест практис, сука.

2018-02-13 14:52 UTC, coffman21 commented on src/main/java/com/banditos/server/bot/BotMessageCreator.java
> +        Iterable<Tusovka> tusovkas = tusovkaRepository.findAll();
Не, разумеется это "лишь бы было". Потом будем отдавать нормальные сообщения.
Отдельный класс - чтобы не городить тысячу методов для разных сообщений внутри класса с ботом.

2018-02-13 14:54 UTC, coffman21 commented on src/main/java/com/banditos/server/parser/AbstractVkParser.java
> +        tusovkaRepository.save(tusovkas);
Почему бы не сохранять? Что ты еще хочешь делать с этими данными, кроме того как сохранить?
Не путай абстрактные классы и интерфейсы.

2018-02-13 14:55 UTC, coffman21 commented on src/main/resources/example-application.properties
> +vk.appid=
Имхо, если не так много пропертей - читается хуже.

2018-02-13 14:57 UTC, coffman21 commented on src/main/resources/example-application.properties
> +vk.appid=
Он же без лишних телодвижений сможет жрать ямл?

2018-02-13 21:52 UTC, minemile commented on pom.xml
> +			<scope>runtime</scope>
Скоп не я добавил.

2018-02-13 21:53 UTC, minemile commented on postgres-docker.sh
> +docker container start psql
Напиши рид ми хоть как заводить вот это все.

2018-02-13 21:54 UTC, minemile commented on src/main/java/com/banditos/server/bot/Bot.java
> +        Bot.telegramToken = env.getProperty("telegram.token");
Зато не пихаешь весь енвайромент в класс.

2018-02-13 21:55 UTC, minemile commented on src/main/resources/example-application.properties
> +vk.appid=
Да.

2018-02-13 22:30 UTC, merged

2018-02-14 10:25 UTC, coffman21 commented on pom.xml
> +			<scope>runtime</scope>
https://github.com/minemile/eventfinder/commit/a02c06b995d5597b648f1f9884d2a9c08a0cabcb#diff-600376dffeb79835ede4a0b285078036

2018-02-14 10:25 UTC, coffman21 commented on postgres-docker.sh
> +docker container start psql
обязательно сделаю

2018-02-14 10:26 UTC, coffman21 commented on src/main/java/com/banditos/server/bot/Bot.java
> +        Bot.telegramToken = env.getProperty("telegram.token");
я пробовал через `@Value`. мне почему-то запомнилось что было как-то еще сильнее через жопу, чем так

2018-02-14 10:27 UTC, coffman21 commented on src/main/resources/example-application.properties
> +vk.appid=
тогда сделай себе application.properties с ямлом! и не еби мозг ))