Create README.md
minemile/eventfinder pull request #3
Opened 2018-02-16 23:06 UTC by coffman21

2018-02-20 19:35 UTC, minemile requested changes

2018-02-20 19:35 UTC, minemile commented on src/main/java/com/banditos/server/parser/AbstractVkParser.java
> +        return tusovka.get(0).getDate();
Нету метода по типу head или first?

2018-02-20 19:35 UTC, minemile commented on src/main/java/com/banditos/server/parser/AbstractVkParser.java
> +        List<Tusovka> tusovka = tusovkaRepository.findByPlaceOrderByDateDesc(place, new PageRequest(0, 1));
Что за PageRequest?

2018-02-20 20:45 UTC, coffman21 commented on src/main/java/com/banditos/server/parser/AbstractVkParser.java
> +        return tusovka.get(0).getDate();
это не совсем тривиальное действие -  
select top(:pageable) * from tusovkas where place = :place order by date desc

2018-02-20 20:47 UTC, coffman21 commented on src/main/java/com/banditos/server/parser/AbstractVkParser.java
> +        List<Tusovka> tusovka = tusovkaRepository.findByPlaceOrderByDateDesc(place, new PageRequest(0, 1));
позволяет дергать из таблиц страницами вместо всей таблицы  
теперь ты можешь достать n последних записей и, узнав у самой последней дату создания поста, сможешь парсить и записывать только нужные строки, отталкиваясь от этой даты

2018-02-21 17:13 UTC, coffman21 commented
смержы, сука

2018-02-21 21:04 UTC, minemile commented
Зарезолви конфликт

2018-02-22 09:30 UTC, merged